# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'room-booking-app'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'roombooking-azure-conn'   # ✅ Your service connection
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'roombooking-azure-conn'   # ✅ Same service connection
    appName: 'roombookingwebapp'                  # ✅ Your App Service name
    containers: 'roombookingcr.azurecr.io/room-booking-app:latest'
