trigger:
- main

variables:
  dockerRegistryServiceConnection: 'roombooking-azure-conn'
  imageRepository: 'room-booking-app'
  containerRegistry: 'roombookingcr.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: BuildAndPush
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push image to ACR
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: buildAndPush
        Dockerfile: $(dockerfilePath)
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: Build
  jobs:
  - job: DeployWebApp
    displayName: Deploy Web App
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'roombooking-azure-conn'
        appName: 'roombookingwebapp'
        containers: 'roombookingcr.azurecr.io/room-booking-app:$(Build.BuildId)'
