# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main   # or your branch name

variables:
  imageRepository: 'roombookingwebapp'
  containerRegistry: 'priyadarshini.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        containerRegistry: 'roombooking-azure-conn'  # Your service connection name
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: Build
  jobs:
  - deployment: DeployWebApp
   # environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy to Web App
            inputs:
              azureSubscription: 'roombooking-azure-conn'  # Your service connection name
              appName: 'roombookingwebapp'                # Your App Service name
              containers: '$(containerRegistry)/$(imageRepository):$(tag)'


